AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application. This template is partially managed by
  Amazon.Lambda.Annotations (v1.3.0.0).
Parameters:
  SendEmailTopicArn:
    Type: String
    Description: ARN of the Send Email topic
Resources:
  LambdaAuthorizer:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: LambdaAuthorizer
      Tool: Amazon.Lambda.Annotations
    Properties:
      Runtime: dotnet8
      CodeUri: s3://onyx-default/3ae9a6d9f256b51772d0c84c7c9ad717
      MemorySize: 512
      Timeout: 30
      Role: arn:aws:iam::975049887576:role/FullAccess
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.Access.AccessFunction_FunctionHandler_Generated::FunctionHandler
  IdentityApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins: '''*'''
        AllowMethods: '''GET,POST,PUT,DELETE,OPTIONS'''
        AllowHeaders: '''Content-Type,Authorization'''
      DefaultRouteSettings:
        DetailedMetricsEnabled: true
      Auth:
        DefaultAuthorizer: LambdaAuthorizer
        Authorizers:
          LambdaAuthorizer:
            FunctionArn:
              Fn::GetAtt:
              - LambdaAuthorizer
              - Arn
            AuthorizerPayloadFormatVersion: '2.0'
    Metadata:
      SamResourceId: IdentityApi
  Login:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: Login
      SyncedEvents:
      - RootPost
      Tool: Amazon.Lambda.Annotations
    Properties:
      Runtime: dotnet8
      CodeUri: s3://onyx-default/3ae9a6d9f256b51772d0c84c7c9ad717
      MemorySize: 512
      Timeout: 30
      Role: arn:aws:iam::975049887576:role/FullAccess
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.Auth.AuthFunctions_Login_Generated::Login
      Environment:
        Variables:
          SendEmailTopicArn:
            Ref: SendEmailTopicArn
      Events:
        RootPost:
          Type: HttpApi
          Properties:
            Path: /api/v1/auth/login
            Method: POST
            ApiId:
              Ref: IdentityApi
            Auth:
              Authorizer: NONE
  Register:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: Register
      SyncedEvents:
      - RootPost
      Tool: Amazon.Lambda.Annotations
    Properties:
      Runtime: dotnet8
      CodeUri: s3://onyx-default/3ae9a6d9f256b51772d0c84c7c9ad717
      MemorySize: 512
      Timeout: 30
      Role: arn:aws:iam::975049887576:role/FullAccess
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.Auth.AuthFunctions_Register_Generated::Register
      Environment:
        Variables:
          SendEmailTopicArn:
            Ref: SendEmailTopicArn
      Events:
        RootPost:
          Type: HttpApi
          Properties:
            Path: /api/v1/auth/register
            Method: POST
            ApiId:
              Ref: IdentityApi
            Auth:
              Authorizer: NONE
  GetUser:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: GetUser
      SyncedEvents:
      - RootGet
      Tool: Amazon.Lambda.Annotations
    Properties:
      Runtime: dotnet8
      CodeUri: s3://onyx-default/3ae9a6d9f256b51772d0c84c7c9ad717
      MemorySize: 512
      Timeout: 30
      Role: arn:aws:iam::975049887576:role/FullAccess
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.User.UserFunctions_GetUser_Generated::GetUser
      Environment:
        Variables:
          SendEmailTopicArn:
            Ref: SendEmailTopicArn
      Events:
        RootGet:
          Type: HttpApi
          Properties:
            Path: /api/v1/user
            Method: GET
            ApiId:
              Ref: IdentityApi
  UpdateUser:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: UpdateUser
      SyncedEvents:
      - RootPut
      Tool: Amazon.Lambda.Annotations
    Properties:
      Runtime: dotnet8
      CodeUri: s3://onyx-default/3ae9a6d9f256b51772d0c84c7c9ad717
      MemorySize: 512
      Timeout: 30
      Role: arn:aws:iam::975049887576:role/FullAccess
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.User.UserFunctions_UpdateUser_Generated::UpdateUser
      Environment:
        Variables:
          SendEmailTopicArn:
            Ref: SendEmailTopicArn
      Events:
        RootPut:
          Type: HttpApi
          Properties:
            Path: /api/v1/user
            Method: PUT
            ApiId:
              Ref: IdentityApi
  RequestEmailChange:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: RequestEmailChange
      SyncedEvents:
      - RootPut
      Tool: Amazon.Lambda.Annotations
    Properties:
      Runtime: dotnet8
      CodeUri: s3://onyx-default/3ae9a6d9f256b51772d0c84c7c9ad717
      MemorySize: 512
      Timeout: 30
      Role: arn:aws:iam::975049887576:role/FullAccess
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.User.UserFunctions_RequestEmailChange_Generated::RequestEmailChange
      Environment:
        Variables:
          SendEmailTopicArn:
            Ref: SendEmailTopicArn
      Events:
        RootPut:
          Type: HttpApi
          Properties:
            Path: /api/v1/user/change-email
            Method: PUT
            ApiId:
              Ref: IdentityApi
  Logout:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: Logout
      SyncedEvents:
      - RootPut
      Tool: Amazon.Lambda.Annotations
    Properties:
      Runtime: dotnet8
      CodeUri: s3://onyx-default/3ae9a6d9f256b51772d0c84c7c9ad717
      MemorySize: 512
      Timeout: 30
      Role: arn:aws:iam::975049887576:role/FullAccess
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.User.UserFunctions_Logout_Generated::Logout
      Environment:
        Variables:
          SendEmailTopicArn:
            Ref: SendEmailTopicArn
      Events:
        RootPut:
          Type: HttpApi
          Properties:
            Path: /api/v1/user/logout
            Method: PUT
            ApiId:
              Ref: IdentityApi
  RemoveUser:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: RemoveUser
      SyncedEvents:
      - RootDelete
      Tool: Amazon.Lambda.Annotations
    Properties:
      Runtime: dotnet8
      CodeUri: s3://onyx-default/3ae9a6d9f256b51772d0c84c7c9ad717
      MemorySize: 512
      Timeout: 30
      Role: arn:aws:iam::975049887576:role/FullAccess
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.User.UserFunctions_RemoveUser_Generated::RemoveUser
      Environment:
        Variables:
          SendEmailTopicArn:
            Ref: SendEmailTopicArn
      Events:
        RootDelete:
          Type: HttpApi
          Properties:
            Path: /api/v1/user/remove
            Method: DELETE
            ApiId:
              Ref: IdentityApi
  VerifyEmail:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: VerifyEmail
      SyncedEvents:
      - RootPut
      Tool: Amazon.Lambda.Annotations
    Properties:
      Runtime: dotnet8
      CodeUri: s3://onyx-default/3ae9a6d9f256b51772d0c84c7c9ad717
      MemorySize: 512
      Timeout: 30
      Role: arn:aws:iam::975049887576:role/FullAccess
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.Auth.AuthFunctions_VerifyEmail_Generated::VerifyEmail
      Environment:
        Variables:
          SendEmailTopicArn:
            Ref: SendEmailTopicArn
      Events:
        RootPut:
          Type: HttpApi
          Properties:
            Path: /api/v1/auth/verify-email
            Method: PUT
            ApiId:
              Ref: IdentityApi
  Refresh:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: Refresh
      SyncedEvents:
      - RootPut
      Tool: Amazon.Lambda.Annotations
    Properties:
      Runtime: dotnet8
      CodeUri: s3://onyx-default/3ae9a6d9f256b51772d0c84c7c9ad717
      MemorySize: 512
      Timeout: 30
      Role: arn:aws:iam::975049887576:role/FullAccess
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.Auth.AuthFunctions_Refresh_Generated::Refresh
      Environment:
        Variables:
          SendEmailTopicArn:
            Ref: SendEmailTopicArn
      Events:
        RootPut:
          Type: HttpApi
          Properties:
            Path: /api/v1/auth/refresh
            Method: PUT
            ApiId:
              Ref: IdentityApi
            Auth:
              Authorizer: NONE
  ResendEmail:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: ResendEmail
      SyncedEvents:
      - RootPut
      Tool: Amazon.Lambda.Annotations
    Properties:
      Runtime: dotnet8
      CodeUri: s3://onyx-default/3ae9a6d9f256b51772d0c84c7c9ad717
      MemorySize: 512
      Timeout: 30
      Role: arn:aws:iam::975049887576:role/FullAccess
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.Auth.AuthFunctions_ResendEmail_Generated::ResendEmail
      Environment:
        Variables:
          SendEmailTopicArn:
            Ref: SendEmailTopicArn
      Events:
        RootPut:
          Type: HttpApi
          Properties:
            Path: /api/v1/auth/resend-email
            Method: PUT
            ApiId:
              Ref: IdentityApi
  ForgotPassword:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: ForgotPassword
      SyncedEvents:
      - RootPut
      Tool: Amazon.Lambda.Annotations
    Properties:
      Runtime: dotnet8
      CodeUri: s3://onyx-default/3ae9a6d9f256b51772d0c84c7c9ad717
      MemorySize: 512
      Timeout: 30
      Role: arn:aws:iam::975049887576:role/FullAccess
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.Auth.AuthFunctions_ForgotPassword_Generated::ForgotPassword
      Environment:
        Variables:
          SendEmailTopicArn:
            Ref: SendEmailTopicArn
      Events:
        RootPut:
          Type: HttpApi
          Properties:
            Path: /api/v1/auth/forgot-password
            Method: PUT
            ApiId:
              Ref: IdentityApi
Outputs:
  ApiURL:
    Description: API endpoint URL for Prod environment
    Value:
      Fn::Sub: https://${IdentityApi}.execute-api.${AWS::Region}.amazonaws.com/
  LambdaAuthorizerArn:
    Description: The ARN of the Lambda Authorizer
    Value:
      Fn::GetAtt:
      - LambdaAuthorizer
      - Arn
